import Head from "next/head";
import React,{useState} from "react";

import App from "../components/Home";
import { firestore } from "../Firestore/firebase";
import { collection, query, getDocs } from "firebase/firestore";

export default function Home() {
  const [data, setData] = React.useState(null);

  const GetData = async () => {
    const q = query(collection(firestore, "startups"));
    const querySnapshort = await getDocs(q);
    const data = querySnapshort.docs.map((data) => {
      return data.data();
    });
    setData(data);
  };
  React.useEffect(() => {
    
    GetData();
}, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data === null ? (
        <h1 style={{textAlign:'center'}}>Loading....</h1>
      ) : ( <App data={data} />)}
    </>
  );
}
